#!/bin/sh

set -e

## partitions

mkfs.ext4 /dev/$ROOT_PART
mkfs.ext4 /dev/$HOME_PART
mkfs.ext4 /dev/$SRC_PART
mkfs.fat -F 32 /dev/$BOOT_PART

mount /dev/$ROOT_PART /mnt/lfs
mkdir -pv /mnt/lfs/{boot,home}
mkdir -pv /mnt/lfs/usr/src
mount /dev/$HOME_PART /mnt/lfs/home 
mount /dev/$BOOT_PART /mnt/lfs/boot
mount /dev/$SRC_PART /mnt/lfs/usr/src

## 3.1 install sources

mkdir -v $LFS/sources
chmod -v a+wt $LFS/sources
wget --input-file=wget-list-systemd --continue --directory-prefix=$LFS/sources

pushd $LFS/sources
  md5sum -c md5sums
popd

chown root:root $LFS/sources/*

## 4.2 creating a limited directory layout in the LFS filesystem

mkdir -pv $LFS/{etc,var} $LFS/usr/{bin,lib,sbin}

for i in bin lib sbin; do
  ln -sv usr/$i $LFS/$i
done

case $(uname -m) in
  x86_64) mkdir -pv $LFS/lib64 ;;
esac

mkdir -pv $LFS/tools

## create LFS user
groupadd lfs
useradd -s /bin/sh -g lfs -m -k /dev/null lfs
passwd lfs

# changing ownership
chown -v lfs $LFS/{usr{,/*},lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  x86_64) chown -v lfs $LFS/lib64 ;;
esac

cat > ~/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
EOF

cat > ~/.bashrc << "EOF"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/usr/bin
if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
PATH=$LFS/tools/bin:$PATH
CONFIG_SITE=$LFS/usr/share/config.site
export LFS LC_ALL LFS_TGT PATH CONFIG_SITE
EOF
